swagger: '2.0'
info:
  title: Go API
  description: API for managing users, deposits, and withdrawals
  version: 1.0.1
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /users:
    get:
      summary: Get all users
      description: Retrieve all users
      responses:
        '200':
          description: A list of users
          schema:
            type: array
            items:
              $ref: '#/definitions/UsersResponse'
  /auth/signup:
    post:
      summary: Sign up a new user
      description: Creates a new user account
      parameters:
        - in: body
          name: user
          description: The user to create
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/UserResponse'

  /auth/login:
    post:
      summary: Log in a user
      description: Authenticates a user and returns a token
      parameters:
        - in: body
          name: credentials
          description: The user's credentials
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/UserResponse'

  /auth/logout:
    delete:
      summary: Log out a user
      description: Invalidates the user's authentication token
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/JSONResponse'

  /deposits:
    get:
      summary: Get filtered deposits
      description: Retrieve a list of deposits based on filters
      parameters:
        - in: query
          name: issuer
          type: integer
          description: Filter by the user who created the deposit
        - in: query
          name: member
          type: integer
          description: Filter by a member of the deposit
        - in: query
          name: min_amount
          type: integer
          description: Filter by minimum deposit amount
        - in: query
          name: max_amount
          type: integer
          description: Filter by maximum deposit amount
        - in: query
          name: description
          type: string
          description: Filter by deposit description (partial match)
        - in: query
          name: created_after
          type: string
          format: date-time
          description: Filter deposits created after a specific timestamp
        - in: query
          name: created_before
          type: string
          format: date-time
          description: Filter deposits created before a specific timestamp
        - in: query
          name: sort_by
          type: string
          description: Sort by a field (e.g., amount, created_at)
          default: created_at
        - in: query
          name: sort_order
          type: string
          description: Sort order (asc or desc)
          default: desc
        - in: query
          name: limit
          type: integer
          description: Limit the number of results (for pagination)
          default: 10
        - in: query
          name: offset
          type: integer
          description: Offset for pagination
          default: 0
      responses:
        '200':
          description: A list of deposits
          schema:
            type: array
            items:
              $ref: '#/definitions/DepositResponse'

    post:
      summary: Create a new deposit
      description: Creates a new deposit transaction
      parameters:
        - in: body
          name: deposit
          description: The deposit to create
          required: true
          schema:
            $ref: '#/definitions/DepositRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/JSONResponse'

    put:
      summary: Update a deposit
      description: Updates an existing deposit transaction
      parameters:
        - in: body
          name: deposit
          description: The deposit to update
          required: true
          schema:
            $ref: '#/definitions/DepositRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/JSONResponse'

    delete:
      summary: Delete a deposit
      description: Deletes a deposit transaction by ID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          description: The ID of the deposit to delete
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/JSONResponse'

  /withdrawals:
    get:
      summary: Get filtered withdrawals
      description: Retrieve a list of withdrawals based on filters
      parameters:
        - in: query
          name: issuer
          type: integer
          description: Filter by the user who created the withdrawal
        - in: query
          name: deposit_id
          type: integer
          description: Filter by the associated deposit ID
        - in: query
          name: min_amount
          type: integer
          description: Filter by minimum withdrawal amount
        - in: query
          name: max_amount
          type: integer
          description: Filter by maximum withdrawal amount
        - in: query
          name: description
          type: string
          description: Filter by withdrawal description (partial match)
        - in: query
          name: created_after
          type: string
          format: date-time
          description: Filter withdrawals created after a specific timestamp
        - in: query
          name: created_before
          type: string
          format: date-time
          description: Filter withdrawals created before a specific timestamp
        - in: query
          name: sort_by
          type: string
          description: Sort by a field (e.g., amount, created_at)
          default: created_at
        - in: query
          name: sort_order
          type: string
          description: Sort order (asc or desc)
          default: desc
        - in: query
          name: limit
          type: integer
          description: Limit the number of results (for pagination)
          default: 10
        - in: query
          name: offset
          type: integer
          description: Offset for pagination
          default: 0
      responses:
        '200':
          description: A list of withdrawals
          schema:
            type: array
            items:
              $ref: '#/definitions/WithdrawalResponse'

    post:
      summary: Create a new withdrawal
      description: Creates a new withdrawal transaction
      parameters:
        - in: body
          name: withdraw
          description: The withdrawal to create
          required: true
          schema:
            $ref: '#/definitions/WithdrawalRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/JSONResponse'

    put:
      summary: Update a withdrawal
      description: Updates an existing withdrawal transaction
      parameters:
        - in: body
          name: withdraw
          description: The withdrawal to update
          required: true
          schema:
            $ref: '#/definitions/WithdrawalRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/JSONResponse'

    delete:
      summary: Delete a withdrawal
      description: Deletes a withdrawal transaction by ID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          description: The ID of the withdrawal to delete
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/WithdrawalResponse'

definitions:
  JSONResponse:
    type: object
    properties:
      status:
        type: string
      description:
        type: string

  UserResponse:
    type: object
    properties:
      status:
        type: string
      description:
        type: string
      result:
        type: object
        properties:
          id:
            type: integer
          username:
            type: string
          password:
            type: string
          email:
            type: string

  UsersResponse:
    type: object
    properties:
      status:
        type: string
      description:
        type: string
      result:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
            username:
              type: string
            password:
              type: string
            email:
              type: string

  DepositResponse:
    type: object
    properties:
      status:
        type: string
      description:
        type: string
      result:
        type: array
        items:
          $ref: '#/definitions/Deposit'

  Deposit:
    type: object
    properties:
      id:
        type: integer
      issuer:
        type: integer
      amount:
        type: integer
      description:
        type: string
      created_at:
        type: string
        format: date-time

  WithdrawalResponse:
    type: object
    properties:
      status:
        type: string
      description:
        type: string
      result:
        type: array
        items:
          $ref: '#/definitions/Withdrawal'

  Withdrawal:
    type: object
    properties:
      id:
        type: integer
      issuer:
        type: integer
      deposit_id:
        type: integer
      amount:
        type: integer
      description:
        type: string
      created_at:
        type: string
        format: date-time

  DepositRequest:
    type: object
    properties:
      issuer:
        type: integer
      members:
        type: array
        items:
          type: integer
      amount:
        type: integer
      description:
        type: string

  WithdrawalRequest:
    type: object
    properties:
      issuer:
        type: integer
      deposit_id:
        type: integer
      amount:
        type: integer
      description:
        type: string